all: pong_signaler ping_signaler

pong_signaler: pong_signaler.cpp
	g++ pong_signaler.cpp -o pong_signaler

ping_signaler: ping_signaler.cpp
	g++ ping_signaler.cpp -o ping_signaler

clear:
	rm -f ping_signaler pong_signaler

